version: '3.8'

services:
  api:
    build: .
    container_name: mon_api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb+srv://apicocktails:gpasdidee@apicocktails.5yszwys.mongodb.net/?retryWrites=true&w=majority&appName=APIcocktails
    networks:
      - mynetwork

  mongo:
    image: mongo:6.0
    container_name: mon_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
